# Generated by Django 5.0.2 on 2024-02-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nonce', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(default='pending', max_length=255)),
                ('check_in_status', models.CharField(default='pending', max_length=255)),
            ],
        ),
    ]
