# Generated by Django 5.0.2 on 2024-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketseller', '0003_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nonce',
            field=models.CharField(max_length=255),
        ),
    ]
